"""Initial database schema

Revision ID: 001
Revises: 
Create Date: 2025-07-17 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forex_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currencies', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('actual', sa.String(length=50), nullable=True),
    sa.Column('forecast', sa.String(length=50), nullable=True),
    sa.Column('previous', sa.String(length=50), nullable=True),
    sa.Column('event_title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currencies', 'date', 'event_title', name='unique_event')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forex_events')
    # ### end Alembic commands ###
