"""add missing notify_minutes columns

Revision ID: a62cb3575eeb
Revises: 20250712_123345
Create Date: 2025-07-13 17:40:10.397772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62cb3575eeb'
down_revision: Union[str, None] = '20250712_123345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notification_settings', sa.Column('notify_15_minutes', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user_notification_settings', sa.Column('notify_30_minutes', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user_notification_settings', sa.Column('notify_60_minutes', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notification_settings', 'notify_60_minutes')
    op.drop_column('user_notification_settings', 'notify_30_minutes')
    op.drop_column('user_notification_settings', 'notify_15_minutes')
    # ### end Alembic commands ###
